### ISSUE TITLE
Infer viaServers from the Matrix room ID

### ISSUE THREAD

**Issue by MadLittleMods** [matrix-org/matrix-appservice-bridge#291]
For most of the intent calls we use a helper `_ensureJoined` to make sure the client is actually in the room before trying to do an action like send a message.

For all of [these calls](https://github.com/matrix-org/matrix-appservice-bridge/blob/ac522565ecc71d43d5cec7f972372acf92877fdd/src/components/intent.ts#L382) except [`intent.join`](https://github.com/matrix-org/matrix-appservice-bridge/blob/ac522565ecc71d43d5cec7f972372acf92877fdd/src/components/intent.ts#L547), we don't pass the `viaServers` option which is necessary in some situations*. And there is **currently no way to forward on the option to `_ensureJoined` even if you wanted to.**

*`viaServers` is necessary when you're trying to join a remote room via an internal ID like `!1234:half-shot.uk` but none of the users on your server have joined it yet. Without `viaServers`, it will fail.

I know that we traditionally do not lookup the `servername` from a internal room ID because they are considered opaque and the originated server doesn't necessarily have to be participating anymore. But I think defaulting to it can get a lot of people out of a random Matrix specific knowledge pitfall.

When I `/join !1234:gitter.im`, I expect it to work no matter what.

## Potential solution

Default the `viaServer` to the servername part of an internal ID: ` !1234:gitter.im` -> `gitter.im`

We already do this to aliases by default `#myalias:gitterim` -> `gitter.im`

## Questions

Should this responsibility be handled wherever we already do the `alias` servername `via` lookup instead?

## Relevant code

 - [`matrix-appservice-bridge` -> `src/components/intent.ts#L796-L798`](https://github.com/matrix-org/matrix-appservice-bridge/blob/ac522565ecc71d43d5cec7f972372acf92877fdd/src/components/intent.ts#L796-L798)
 - [`matrix-js-sdk` -> `src/client.js#L2528-L2530`](https://github.com/matrix-org/matrix-js-sdk/blob/ff6612f9d0aa1a7c08b65a0b41c5ab997506016f/src/client.js#L2528-L2530)

---

This issue is a result of me running into this problem as discussed in https://matrix.to/#/!vYjRCIoySolvxmhMJE:matrix.org/$lKK3lLkXYwh__Td8zO8kRx6yXR-ZO9yLPX1-2uSS-ck?via=matrix.org&via=vector.modular.im&via=half-shot.uk

**Comment by Half-Shot** [comment]
So first and foremost the server lookups are performed by the homeserver and typically it's not the responsibility of the bridge lib to determine which servers to contact. Part of me wants to say we should fix this as the homeserver level for anyone trying to do a `/join !foo:matrix.org` in their client.

If there remains reasons why the homeserver does not want to do this, it would probably stand to reason that the bridge lib shouldn't be doing this either. If bridge implementations wish to go ahead anyway, I'd probably suggest they do a split operation and pass it in with `viaServer`.

>**For most of the intent calls we use a helper _ensureJoined to make sure the client is actually in the room before trying to do an action like send a message.

> For all of these calls except intent.join, we don't pass the viaServers option which is necessary in some situations*. And there is currently no way to forward on the option to _ensureJoined even if you wanted to.**

Typically speaking we expect that the first join by the bridge to a foreign room would be initiated via a join call in response to an invite. Joining a room from an invite will always work since it provides the necessary information. `_ensureJoined` is typically more designed for ghost bridge users who are joining a room after doing an action, where the room is already considered bridged.

It might be better to look at the design of your bridge and decide if you *need* to join a room without a third party user inviting it. E.g. for plumbing on the IRC/Slack side we get the matrix user to invite the bridge into the room first. Other bridges require you set an alias.

**Comment by MadLittleMods** [comment]
> It might be better to look at the design of your bridge and decide if you need to join a room without a third party user inviting it. E.g. for plumbing on the IRC/Slack side we get the matrix user to invite the bridge into the room first. Other bridges require you set an alias.

Coming at this without the prior know-how of other bridges, I feel like it's an arbitrary limitation that ends up tripping me up and probably others in the future. I'm fortunate enough to be able to ask the source what's going on and move past it quickly. Even with the invitation route, it has to be implemented in your bridge to accept the invite in addition to the manual action.

The existing patterns are valid and `viaServer` is a useful feature but I think joining an internal room ID should just work by default for a majority case. This cuts down on domain specific knowledge and code necessary for a successful bridge.

---

> Part of me wants to say we should fix this as the homeserver level for anyone trying to do a` /join !foo:matrix.org` in their client.

Agreed for moving as close as possible to where the `alias` servername lookup happens as well 👍

**Comment by MadLittleMods** [comment]
Regardless of whether this is a useful feature, the spec is leaning towards changing internal room ID's to public keys which won't have this information in the future. And will require a more specific solution for routing.
